title: kaki-epithesi
description: "Persoanal Blog"
author:
  name: "Abhijit Roy"
  email: "kakiepithesi@gamil.com"
  url: "https://kaki-epithesi.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Abhijit Roy"
year : "2020"
